### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by 124399839** [murari023/MotionRec#1]
Dear Murari，
    Thank you so much for your excellent work, which inspired me a lot.When to update the code completely? Thank you very much.

**Comment by murari023** [comment]
Hi,
Thanks for your interest. We are in the process of making the code public. Hopefully, it will be ready by next week. You can drop a comment if the code is not uploaded by then.

**Comment by murari023** [comment]
Source Code available here!
https://github.com/murari023/MotionRec-1
